accounts/urls.py
"""Defines URL patterns for accounts."""

from django.urls import path, include

from . import views

app_name = 'accounts'
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
]

blog_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('blogs.urls')),
]

blogs/urls.py
"""Defines URL paths for blogs"""

from django.urls import path

from . import views

app_name = 'blogs'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    # Shows all blogs.
    path('blogs/', views.blogs, name="blogs"),
    # Shows all the blog posts for a blog.
    path('blogs/<int:blog_id>/', views.blogposts, name="blogposts"),
    # Page for creating a new blog.
    path('new_blog/', views.new_blog, name='new_blog'),
    # Path for creating new blog posts.
    path('new_post/<int:blog_id>/', views.new_post, name='new_post'),
    # Path for editing past blog posts.
    path('edit_post/<int:post_id>/', views.edit_post, name='edit_post'),
]

accounts/models.py
from django.db import models

# Create your models here.

blogs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Blog(models.Model):
    """Blueprint for a basic blog."""
    text = models.CharField(max_length=200)
    date_created = models.DateField(auto_now_add=True)
    owner = models.ForeignKey(to=User, on_delete=models.CASCADE)

    def __str__(self):
        """Returns the name of the blog."""
        return self.text

class BlogPost(models.Model):
    """Basic blog post. Relates to a blog"""
    blog = models.ForeignKey(to=Blog, on_delete=models.CASCADE)
    text = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Returns a simple representation of the blog post."""
        if len(self.text) > 50:
            return (f"{self.text[:50]}...")
        else:
            return f"{self.text}"

blogs/forms.py
"""Forms for the blog app."""
from django import forms

from .models import Blog, BlogPost

class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['text']
        labels = {'text':''}

class PostForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['text']
        labels = {'text':''}
        widget = {'text': forms.Textarea(attrs={'cols': 80})}

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

def register(request):
    if request.method != 'POST':
        # Send blank registration form.
        form = UserCreationForm()
    else:
        # Process completed form
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            # Login user and redirect to home page.
            login(request, new_user)
            return redirect('blogs:index')
    
    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'registration/register.html', context)

blogs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import Blog, BlogPost
from .forms import BlogForm, PostForm

def check_blog_owner(blog, request):
    """Page will not load if the user does not own the blog."""
    if blog.owner != request.user:
        raise Http404

def index(request):
    # Home page for blogs.
    return render(request, 'blogs/index.html')

def blogs(request):
    # Shows all created blogs.
    blogs = Blog.objects.order_by('date_created')
    context = {'blogs': blogs}
    return render(request, 'blogs/blogs.html', context)

def blogposts(request, blog_id):
    # Shows all the posts created by a blog.
    blog = Blog.objects.get(id=blog_id)
    posts = blog.blogpost_set.order_by('-date_created')
    context = {'blog': blog, 'posts': posts}
    return render(request, 'blogs/blogposts.html', context)

@login_required
def new_blog(request):
    # Allows user to create a new blog.
    if request.method != 'POST':
        # No input given, create new blog form.
        form = BlogForm()
    else:
        form = BlogForm(data=request.POST)
        if form.is_valid():
            new_blog = form.save(commit=False)
            new_blog.owner = request.user
            new_blog.save()
            return redirect('blogs:blogs')
    
    # Return a blank or invalid form
    context = {'form': form}
    return render(request, 'blogs/new_blog.html', context)

@login_required
def new_post(request, blog_id):
    # Allows users to create posts in their blogs.
    blog = Blog.objects.get(id=blog_id)
    check_blog_owner(blog, request)

    if request.method != 'POST':
        # No input given, create new blogpost form
        form = PostForm()
    else:
        form = PostForm(data=request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.blog = blog
            post.save()
            return redirect('blogs:blogposts', blog_id=blog_id)

    # Display the blank or invalid form.
    context = {'blog': blog, 'form': form}
    return render(request, 'blogs/new_post.html', context)

@login_required
def edit_post(request, post_id):
    # Allows users to create posts in their blogs.
    blogpost = BlogPost.objects.get(id=post_id)
    blog = blogpost.blog
    check_blog_owner(blog, request)

    if request.method != 'POST':
        # No input given, create new blogpost form
        form = PostForm(instance=blogpost)
    else:
        form = PostForm(instance=blogpost, data=request.POST)
        if form.is_valid():
            form = form.save()
            return redirect('blogs:blogposts', blog_id=blog.id)

    # Display the blank or invalid form.
    context = {'blogpost': blogpost, 'blog': blog, 'form': form}
    return render(request, 'blogs/edit_post.html', context)

blogs/templates/blogs/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width-device-width, initial-scale=1">
  <title>Blogs for Everyone</title>

  {% load django_bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_javascript %}
    
</head>
<body>
  <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'blogs:index' %}">
            Blogs for Everyone</a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
          data-bs-target="#navbarCollapse" aria-controls="navbarCollapse"
          aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav me-auto mb-2 mb-md-0">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blogs:blogs' %}">
                Blogs</a></li>
            </ul> <!-- End of links on left side of navbar -->

            <!-- Account-related links -->
            <ul class="navbar-nav ms-auto mb-2 mb-md-0">

              {% if user.is_authenticated %}
                <li class="nav-item">
                  <span class="navbar-text me-2">Hello, {{ user.username }}.
                    </span></li>
              {% else %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:register' %}">
                        Register</a></li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:login' %}">
                        Log in</a></li>
              {% endif %}

            </ul> <!-- End of account-related links -->
             {% if user.is_authenticated %}
               <form action="{% url 'accounts:logout' %}" method="post">
                {% csrf_token %}
                <button name="submit" class="btn btn-outline-secondary btn-sm">
                    Log out</button>
                </form>
              {% endif %}

        </div> <!-- Closes collapsible parts of navbar -->

    </div> <!-- Closes navbar's container -->
  </nav> <!-- End of navbar -->

  <main class="container">
    <div class="pb-2 mb-2 border-bottom">
      {% block page_header %}{% endblock page_header %}
    </div>
    <div>
      {% block content %}{% endblock content %}
    </div>
  </main>
  
</body>
</html>

blogs/templates/blogs/blogposts.html
{% extends 'blogs/base.html' %}

{% block page_header %}
  <h1>{{ blog.text }}</h1>
{% endblock page_header %}

{% block content %}

  {% if blog.owner == request.user %}
    <p>
      <a href="{% url 'blogs:new_post' blog.id %}">Add a new post:</a>
    </p>
  {% endif %}

    {% for post in posts %}
      <div class="card mb-3">
        <!-- Card header with timestamp and edit link -->
        <h4 class="card-header">
          {{ post.date_created|date:'M d, Y H:i' }}
          {% if blog.owner == request.user %}
            <small><a href="{% url 'blogs:edit_post' post.id %}">
              edit post</a></small>
          {% endif %}
        </h4>
        <!-- Card body with entry text -->
        <div class="card-body">{{ post.text|linebreaks }}</div>
      </div>
    {% empty %}
      <p>There are no posts for this blog yet.<p>
    {% endfor %}

{% endblock content %}

blogs/templates/blogs/blogs.html
{% extends 'blogs/base.html' %}

{% block page_header %}
  <h1>Blogs</h1>
{% endblock page_header %}

{% block content %}

  <ul class="list-group border-bottom pb-2 mb-4">
    {% for blog in blogs %}
    <li class="list-group-item border-0">
      <a href="{% url 'blogs:blogposts' blog.id %}">
        {{ blog.text }}</a>
    </li>
    {% empty %}
      <li class="list-group-item border-0">No blogs have been created yet.</li>
    {% endfor %}
  </ul>

  <a href="{% url 'blogs:new_blog' %}">Create a new blog</a>

{% endblock content %}

blogs/templates/blogs/edit_post.html
{% extends 'blogs/base.html' %}
{% load django_bootstrap5 %}

{% block page_header %}
  <h2><a href="{% url 'blogs:blogposts' blog.id %}">{{ blog }}</a></h2>
  <h2>Edit Post</h2>
{% endblock page_header %}


{% block content %}

  <form action="{% url 'blogs:edit_post' blogpost.id %}" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="Save" %}
  </form>

{% endblock content %}

blogs/templates/blogs/index.html
{% extends "blogs/base.html" %}

{% block page_header %}
  <div class="p-3 mb-4 bg-light border rounded-3">
    <div class="container-fluid py-4">
      <h1 class="display-3">Create a blog for anything.</h1>

      <p class="lead">Start your own blog, and add whatever is on your mind.
      Whether you're hiking the Grand Canyon, making yourself a
      matchbox car raceway, or digging up some old family albums,
      we want to hear it. </p>
      
      <a class="btn btn-primary btn-lg mt-1"
        href="{% url 'accounts:register' %}">Register &raquo;</a>
    </div>
  </div>
{% endblock page_header %}

blogs/templates/blogs/new_blog.html
{% extends 'blogs/base.html' %}
{% load django_bootstrap5 %}

{% block page_header %}
  <h2>New Blog</h2>
{% endblock page_header %}

{% block content %}

  <p>Create a new blog:</p>

  <form action="{% url 'blogs:new_blog' %}" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="Create" %}
  </form>

{% endblock content %}

blogs/templates/blogs/new_post.html
{% extends 'blogs/base.html' %}
{% load django_bootstrap5 %}

{% block page_header %}
  <h2>New Post</h2>
{% endblock page_header %}


{% block content %}

  <p>
    <a href="{% url 'blogs:blogposts' blog.id %}">{{ blogpost }}</a>
  </p>

  <form action="{% url 'blogs:new_post' blog.id %}" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="Add post"%}
  </form>

{% endblock content %}

templates/505.html
{% extends 'blogs/base.html' %}

{% block page_header %}

  <h2>There has been an internal error. (505)</h2>
  
{% endblock page_header %}